# April 19, 2021 Create a new geom ---

# It’s easiest to start with a simple example. The code below is a simplified version of geom_point():

GeomSimplePoint <- ggproto("GeomSimplePoint", Geom,
                           required_aes = c("x", "y"),
                           default_aes = aes(shape = 19, colour = "black"),
                           draw_key = draw_key_point,
                           
                           draw_panel = function(data, panel_params, coord) {
                               coords <- coord$transform(data, panel_params)
                               grid::pointsGrob(
                                   coords$x, coords$y,
                                   pch = coords$shape,
                                   gp = grid::gpar(col = coords$colour)
                               )
                           }
)

geom_simple_point <- function(mapping = NULL, data = NULL, stat = "identity",
                              position = "identity", na.rm = FALSE, show.legend = NA, 
                              inherit.aes = TRUE, ...) {
    layer(
        geom = GeomSimplePoint, mapping = mapping,  data = data, stat = stat, 
        position = position, show.legend = show.legend, inherit.aes = inherit.aes,
        params = list(na.rm = na.rm, ...)
    )
}

ggplot(mpg, aes(displ, hwy)) + 
    geom_simple_point()


# This is very similar to defining a new stat. You always need to provide fields/methods for the four pieces shown above:
# required_aes is a character vector which lists all the aesthetics that the user must provide.
# default_aes lists the aesthetics that have default values.
# draw_key provides the function used to draw the key in the legend. You can see a list of all the build in key functions in ?draw_key
# draw_panel() is where the magic happens. This function takes three arguments and returns a grid grob. It is called once for each panel. 
# It’s the most complicated part and is described in more detail below.

#draw_panel() has three arguments:
#data: a data frame with one column for each aesthetic.
#panel_params: a list of per-panel parameters generated by the coord. You should consider this an opaque data structure: don’t look inside it, just pass along to coord methods.
#coord: an object describing the coordinate system.

#You need to use panel_params and coord together to transform the data 
#coords <- coord$transform(data, panel_params). This creates a data frame 
#where position variables are scaled to the range 0–1. You then take this data 
#and call a grid grob function. (Transforming for non-Cartesian coordinate systems 
#is quite complex - you’re best off transforming your data to the form accepted 
#by an existing ggplot2 geom and passing it.)


#Overriding draw_panel() is most appropriate if there is one graphic element per row. In other cases, you want graphic element per group. For example, take polygons: each row gives one vertex of a polygon. In this case, you should instead override draw_group().

#The following code makes a simplified version of GeomPolygon:

GeomSimplePolygon <- ggproto("GeomPolygon", Geom,
                             required_aes = c("x", "y"),
                             
                             default_aes = aes(
                                 colour = NA, fill = "grey20", size = 0.5,
                                 linetype = 1, alpha = 1
                             ),
                             
                             draw_key = draw_key_polygon,
                             
                             draw_group = function(data, panel_params, coord) {
                                 n <- nrow(data)
                                 if (n <= 2) return(grid::nullGrob())
                                 
                                 coords <- coord$transform(data, panel_params)
                                 # A polygon can only have a single colour, fill, etc, so take from first row
                                 first_row <- coords[1, , drop = FALSE]
                                 
                                 grid::polygonGrob(
                                     coords$x, coords$y, 
                                     default.units = "native",
                                     gp = grid::gpar(
                                         col = first_row$colour,
                                         fill = scales::alpha(first_row$fill, first_row$alpha),
                                         lwd = first_row$size * .pt,
                                         lty = first_row$linetype
                                     )
                                 )
                             }
)
geom_simple_polygon <- function(mapping = NULL, data = NULL, stat = "chull",
                                position = "identity", na.rm = FALSE, show.legend = NA, 
                                inherit.aes = TRUE, ...) {
    layer(
        geom = GeomSimplePolygon, mapping = mapping, data = data, stat = stat, 
        position = position, show.legend = show.legend, inherit.aes = inherit.aes,
        params = list(na.rm = na.rm, ...)
    )
}

ggplot(mpg, aes(displ, hwy)) + 
    geom_point() + 
    geom_simple_polygon(aes(colour = class), fill = NA)

#Inheriting from an existing Geom
#Sometimes you just want to make a small modification to an existing geom. 
# In this case, rather than inheriting from Geom you can inherit from an existing subclass. 
# For example, we might want to change the defaults for GeomPolygon to work better with StatChull:

GeomPolygonHollow <- ggproto("GeomPolygonHollow", GeomPolygon,
                             default_aes = aes(colour = "black", fill = NA, size = 0.5, linetype = 1,
                                               alpha = NA)
)
geom_chull <- function(mapping = NULL, data = NULL, 
                       position = "identity", na.rm = FALSE, show.legend = NA, 
                       inherit.aes = TRUE, ...) {
    layer(
        stat = StatChull, geom = GeomPolygonHollow, data = data, mapping = mapping,
        position = position, show.legend = show.legend, inherit.aes = inherit.aes,
        params = list(na.rm = na.rm, ...)
    )
}

ggplot(mpg, aes(displ, hwy)) + 
    geom_point() + 
    geom_chull()


# read post from (https://rpubs.com/AndersonUyekita/jhu_build_a_new_geom) ---


